services:
  mongo:
    image: mongo:6
    container_name: parcial_mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  # ============================
  #        ITEMS SERVICES
  # ============================
  create_items:
    build: ./services/items/create
    container_name: create_items_service
    depends_on:
      mongo:
        condition: service_healthy
    environment:
      CREATE_PORT: ${CREATE_PORT_ITEMS}
      MONGO_HOST: mongo
      MONGO_PORT: 27017
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    ports:
      - "${CREATE_PORT_ITEMS}:${CREATE_PORT_ITEMS}"

  read_items:
    build: ./services/items/read
    container_name: read_items_service
    depends_on:
      mongo:
        condition: service_healthy
    environment:
      READ_PORT: ${READ_PORT_ITEMS}
      MONGO_HOST: mongo
      MONGO_PORT: 27017
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    ports:
      - "${READ_PORT_ITEMS}:${READ_PORT_ITEMS}"

  update_items:
    build: ./services/items/update
    container_name: update_items_service
    depends_on:
      mongo:
        condition: service_healthy
    environment:
      UPDATE_PORT: ${UPDATE_PORT_ITEMS}
      MONGO_HOST: mongo
      MONGO_PORT: 27017
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    ports:
      - "${UPDATE_PORT_ITEMS}:${UPDATE_PORT_ITEMS}"

  delete_items:
    build: ./services/items/delete
    container_name: delete_items_service
    depends_on:
      mongo:
        condition: service_healthy
    environment:
      DELETE_PORT: ${DELETE_PORT_ITEMS}
      MONGO_HOST: mongo
      MONGO_PORT: 27017
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    ports:
      - "${DELETE_PORT_ITEMS}:${DELETE_PORT_ITEMS}"

  # ============================
  #      STUDENTS SERVICES
  # ============================
  create_students:
    build: ./services/students/create
    container_name: create_students_service
    depends_on:
      mongo:
        condition: service_healthy
    environment:
      CREATE_PORT: ${CREATE_PORT_STUDENTS}
      MONGO_HOST: mongo
      MONGO_PORT: 27017
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    ports:
      - "${CREATE_PORT_STUDENTS}:${CREATE_PORT_STUDENTS}"

  read_students:
    build: ./services/students/read
    container_name: read_students_service
    depends_on:
      mongo:
        condition: service_healthy
    environment:
      READ_PORT: ${READ_PORT_STUDENTS}
      MONGO_HOST: mongo
      MONGO_PORT: 27017
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    ports:
      - "${READ_PORT_STUDENTS}:${READ_PORT_STUDENTS}"

  update_students:
    build: ./services/students/update
    container_name: update_students_service
    depends_on:
      mongo:
        condition: service_healthy
    environment:
      UPDATE_PORT: ${UPDATE_PORT_STUDENTS}
      MONGO_HOST: mongo
      MONGO_PORT: 27017
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    ports:
      - "${UPDATE_PORT_STUDENTS}:${UPDATE_PORT_STUDENTS}"

  delete_students:
    build: ./services/students/delete
    container_name: delete_students_service
    depends_on:
      mongo:
        condition: service_healthy
    environment:
      DELETE_PORT: ${DELETE_PORT_STUDENTS}
      MONGO_HOST: mongo
      MONGO_PORT: 27017
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    ports:
      - "${DELETE_PORT_STUDENTS}:${DELETE_PORT_STUDENTS}"


  # ============================
  #      MASCOTAS SERVICES
  # ============================
  create_mascotas:
    build: ./services/mascotas/create
    container_name: create_mascotas_service
    depends_on:
      mongo:
        condition: service_healthy
    environment:
      CREATE_PORT: ${CREATE_PORT_MASCOTAS}
      MONGO_HOST: mongo
      MONGO_PORT: 27017
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    ports:
      - "${CREATE_PORT_MASCOTAS}:${CREATE_PORT_MASCOTAS}"

  read_mascotas:
    build: ./services/mascotas/read
    container_name: read_mascotas_service
    depends_on:
      mongo:
        condition: service_healthy
    environment:
      READ_PORT: ${READ_PORT_MASCOTAS}
      MONGO_HOST: mongo
      MONGO_PORT: 27017
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    ports:
      - "${READ_PORT_MASCOTAS}:${READ_PORT_MASCOTAS}"

  update_mascotas:
    build: ./services/mascotas/update   
    container_name: update_mascotas_service
    depends_on:
      mongo:
        condition: service_healthy  
    environment:
      UPDATE_PORT: ${UPDATE_PORT_MASCOTAS}
      MONGO_HOST: mongo
      MONGO_PORT: 27017
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    ports:
      - "${UPDATE_PORT_MASCOTAS}:${UPDATE_PORT_MASCOTAS}"

  delete_mascotas:
    build: ./services/mascotas/delete
    container_name: delete_mascotas_service
    depends_on:
      mongo:
        condition: service_healthy
    environment:
      DELETE_PORT: ${DELETE_PORT_MASCOTAS}
      MONGO_HOST: mongo
      MONGO_PORT: 27017
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    ports:
      - "${DELETE_PORT_MASCOTAS}:${DELETE_PORT_MASCOTAS}"
    
   
volumes:
  mongo_data:
