# Build stage
FROM golang:1.25-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o /bin/create-service ./cmd

# Final stage
FROM scratch
COPY --from=builder /bin/create-service /create-service
EXPOSE 8081
ENTRYPOINT ["/create-service"]
